### ISSUE TITLE
Specification of default input dataset.

### ISSUE THREAD

**Issue by dietervdb-meteo** [ecmwf/anemoi-inference#49]
### Is your feature request related to a problem? Please describe.

In the feature/refactor branch , if one chooses to run inference from an anemoi-dataset then if no further specifications are given the default dataset to take as input is the one used during training as specified in the checkpoint. Currently this is taken literally as to be also the period used for training. Typically one wants to do inference on the same dataset but in a period outside that used for training [or validation], which is specified as the test period in the training config.

### Describe the solution you'd like

Either remove `start` and `end` from the dataset meta date when loading it from the checkpoint, or, and this is maybe better, make the test period as specified in the dataloader config the default.

**Comment by frazane** [comment]
I believe this issue is no longer relevant as the current configuration (introduced in #33) requires users to explicitly specify the input type (training, validation or test) and simply specifying `dataset: true` is no longer supported. Should we close this?

However note that the docs still requires some updates, e.g. [here](https://anemoi-inference.readthedocs.io/en/latest/apis/level3.html).

**Comment by dietervdb-meteo** [comment]
@b8raoult what is the current status of this issue? Can we close it?

**Comment by dietervdb-meteo** [comment]
Closing
